### ISSUE TITLE
Can I have this?

### ISSUE THREAD

**Issue by Darkosto** [NovaMachina-Mods/ExNihiloSequentia-Thermal#1]
Hi!

I would love to be able to  try out this addon since I am using a modpack with Thermal in it. Any chance this will be available soon?

Thanks!
Darkosto

**Comment by NovaMachina** [comment]
For sure! Its pretty close, I just need to add in crushed obsidian since Thermal Foundation doesn't have it in it.

**Comment by NovaMachina** [comment]
@Darkosto I just pushed a release. Should be available on CurseForge soon.

**Comment by Darkosto** [comment]
Thank you so much!!!
